# Generated by Django 4.2.3 on 2023-07-30 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=50, verbose_name='Refenence number')),
                ('chinese_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chinese name')),
                ('english_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='English name')),
                ('revenue_sharing', models.IntegerField(verbose_name='Revenue sharing')),
                ('br_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='BR no.')),
                ('br_expiry_date', models.DateField(blank=True, null=True, verbose_name='BR Expiry Date')),
                ('company_type', models.CharField(blank=True, choices=[('sole_proprietorships', 'Sole Proprietorships'), ('partnerships ', 'Partnerships '), ('limited_company', 'Limited Company')], max_length=50, null=True, verbose_name='Company Type')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Address')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='BR Expiry Date')),
                ('tvp_contact_no', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 8 digits.', regex='^\\d{8}$')], verbose_name='TVP contact phone number')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email')),
                ('company_email_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Email Password')),
                ('tvp_registerd_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='TVP Registered Email')),
                ('tvp_registerd_email_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='TVP Registerd Email Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefererProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referrer name')),
                ('referral_times', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_chinese_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Owner Chinese name')),
                ('owner_english_name', models.CharField(max_length=50, verbose_name='Owner English name')),
                ('phone', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 8 digits.', regex='^\\d{8}$')])),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('ref_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_set', to='data.customerprofile', verbose_name='Owners')),
            ],
            options={
                'verbose_name': 'owner profile',
                'verbose_name_plural': 'owners profiles',
                'ordering': ['-shares'],
            },
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='Referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrer_set', to='data.refererprofile'),
        ),
        migrations.CreateModel(
            name='CustomerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_bank_ac', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Bank Account')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_changes', models.TextField(blank=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.customerprofile')),
            ],
        ),
    ]
