# Generated by Django 4.2.3 on 2023-07-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='Referrer',
            new_name='referrer',
        ),
    ]
