# Generated by Django 4.2.3 on 2023-07-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_referrer_customerprofile_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refererprofile',
            old_name='referer_name',
            new_name='referrer_name',
        ),
    ]
