# Generated by Django 4.2.3 on 2023-07-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_referer_name_refererprofile_referrer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='refererprofile',
            name='ref_no',
            field=models.CharField(default=1, max_length=50, verbose_name='Refenence number'),
            preserve_default=False,
        ),
    ]
