# Generated by Django 4.2.3 on 2023-07-30 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_refererprofile_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerledger',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customerledger',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='customerledger',
            name='transaction_type',
        ),
        migrations.CreateModel(
            name='BalanceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_receiver_set', to='data.customerledger')),
            ],
        ),
    ]
