# Generated by Django 4.2.3 on 2023-07-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_customerledger_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancechange',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_receiver_set', to='data.customerprofile'),
        ),
    ]
