# Generated by Django 4.2.3 on 2023-07-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_balancechange_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
